image: "docker:latest"
services:
  - "docker:dind"

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay

build:
  only:
    - master
  script:
    - "docker login -u gitlab-ci-token -p \"$CI_BUILD_TOKEN\" \"$CI_REGISTRY\""
    - "docker build -t \"$CI_REGISTRY_IMAGE:latest\" ."
    - "docker push \"$CI_REGISTRY_IMAGE:latest\""
  stage: build

deploy:
  image: alpine
  only:
    - master
  script:
    - "apk add --no-cache curl wget"
    - "curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    - "chmod +x ./kubectl"
    - "mv ./kubectl /usr/local/bin/kubectl"
    - "wget --header \"Content-Type: application/json\" --header \"Authorization: Bearer $DIGITALOCEAN_TOKEN\" \"https://api.digitalocean.com/v2/kubernetes/clusters/b9a8389f-646a-47ba-85ec-ec2de6866e75/kubeconfig\""
    - "kubectl --kubeconfig=./kubeconfig rollout restart statefulset/freethewumpus"
  stage: deploy
