apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: freethewumpus-redis
  labels:
    run: freethewumpus-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      run: freethewumpus-redis
  template:
    metadata:
      labels:
        run: freethewumpus-redis
    spec:
      containers:
      - name: freethewumpus-redis
        image: redis:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: freethewumpus-redis
  labels:
    run: freethewumpus-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    run: freethewumpus-redis
