apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freethewumpus
spec:
  replicas: 4
  serviceName: freethewumpus
  selector:
    matchLabels:
      run: freethewumpus
  template:
    metadata:
      labels:
        run: freethewumpus
    spec:
      containers:
        - name: freethewumpus
          image: registry.gitlab.com/freethewumpus/web
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              port: 8000
              path: /
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              port: 8000
              path: /
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: RETHINK_HOST
              value: rethinkdb-rethinkdb-cluster
            - name: RETHINKDB_PASSWORD
              value: rethinkdb
            - name: REDIS_HOST
              value: freethewumpus-redis:6379
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: freethewumpus
                  key: secret_access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: freethewumpus
                  key: secret_access_key
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: freethewumpus
                  key: access_key_id
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: freethewumpus
                  key: bucket
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: freethewumpus
                  key: endpoint
      imagePullSecrets:
        - name: gitlab
